library(stringr)
library(ggplot2)
dir("LD_decay_chr2")
chr2.tb <- read.delim("LD_decay_chr2/tobacco-thin2.ld.summary",sep="",header=F,check.names=F,stringsAsFactors=F)
chr2.pe <- read.delim("LD_decay_chr2/peach-thin2.ld.summary",sep="",header=F,check.names=F,stringsAsFactors=F)
chr2.pe <- read.delim("LD_decay_chr4/peach-thin2.ld.summary",sep="",header=F,check.names=F,stringsAsFactors=F)
chr2.pe <- read.delim("LD_decay_chr2/peach-thin2.ld.summary",sep="",header=F,check.names=F,stringsAsFactors=F)
chr4.pe <- read.delim("LD_decay_chr4/peach-thin2.ld.summary",sep="",header=F,check.names=F,stringsAsFactors=F)
chr4.tb <- read.delim("LD_decay_chr4/tobacco-thin2.ld.summary",sep="",header=F,check.names=F,stringsAsFactors=F)
chr5.pe <- read.delim("LD_decay_chr5/peach-thin2.ld.summary",sep="",header=F,check.names=F,stringsAsFactors=F)
chr5.tb <- read.delim("LD_decay_chr5/tobacco-thin2.ld.summary",sep="",header=F,check.names=F,stringsAsFactors=F)
chr6.tb <- read.delim("LD_decay_chr6/tobacco-thin2.ld.summary",sep="",header=F,check.names=F,stringsAsFactors=F)
chr6.pe <- read.delim("LD_decay_chr6/peach-thin2.ld.summary",sep="",header=F,check.names=F,stringsAsFactors=F)
chr3.pe <- read.delim("peach-thin.ld.summary",sep="",header=F,check.names=F,stringsAsFactors=F)
chr3.tb <- read.delim("tobacco-thin.ld.summary",sep="",header=F,check.names=F,stringsAsFactors=F)
colnames(chr2.pe) <- c("dist","rsq")
colnames(chr2.tb) <- c("dist","rsq")
colnames(chr3.pe) <- c("dist","rsq")
colnames(chr3.tb) <- c("dist","rsq")
colnames(chr4.pe) <- c("dist","rsq")
colnames(chr4.tb) <- c("dist","rsq")
colnames(chr5.pe) <- c("dist","rsq")
colnames(chr5.tb) <- c("dist","rsq")
colnames(chr6.pe) <- c("dist","rsq")
colnames(chr6.tb) <- c("dist","rsq")
chr2.pe$distc <- cut(chr2.pe$dist,breaks=seq(from=min(chr2.pe$dist)-1,to=max(chr2.pe$dist)+1,by=100000))
chr3.pe$distc <- cut(chr3.pe$dist,breaks=seq(from=min(chr3.pe$dist)-1,to=max(chr3.pe$dist)+1,by=100000))
chr4.pe$distc <- cut(chr4.pe$dist,breaks=seq(from=min(chr4.pe$dist)-1,to=max(chr4.pe$dist)+1,by=100000))
chr5.pe$distc <- cut(chr5.pe$dist,breaks=seq(from=min(chr5.pe$dist)-1,to=max(chr5.pe$dist)+1,by=100000))
chr6.pe$distc <- cut(chr6.pe$dist,breaks=seq(from=min(chr6.pe$dist)-1,to=max(chr6.pe$dist)+1,by=100000))
chr2.tb$distc <- cut(chr2.tb$dist,breaks=seq(from=min(chr2.tb$dist)-1,to=max(chr2.tb$dist)+1,by=100000))
chr3.tb$distc <- cut(chr3.tb$dist,breaks=seq(from=min(chr3.tb$dist)-1,to=max(chr3.tb$dist)+1,by=100000))
chr4.tb$distc <- cut(chr4.tb$dist,breaks=seq(from=min(chr4.tb$dist)-1,to=max(chr4.tb$dist)+1,by=100000))
chr5.tb$distc <- cut(chr5.tb$dist,breaks=seq(from=min(chr5.tb$dist)-1,to=max(chr5.tb$dist)+1,by=100000))
chr6.tb$distc <- cut(chr6.tb$dist,breaks=seq(from=min(chr6.tb$dist)-1,to=max(chr6.tb$dist)+1,by=100000))
chr2.pe1 <- chr2.pe %>% group_by(distc) %>% summarise(mean=mean(rsq),median=median(rsq))
chr3.pe1 <- chr3.pe %>% group_by(distc) %>% summarise(mean=mean(rsq),median=median(rsq))
chr4.pe1 <- chr4.pe %>% group_by(distc) %>% summarise(mean=mean(rsq),median=median(rsq))
chr5.pe1 <- chr5.pe %>% group_by(distc) %>% summarise(mean=mean(rsq),median=median(rsq))
chr6.pe1 <- chr6.pe %>% group_by(distc) %>% summarise(mean=mean(rsq),median=median(rsq))
chr2.tb1 <- chr2.tb %>% group_by(distc) %>% summarise(mean=mean(rsq),median=median(rsq))
chr3.tb1 <- chr3.tb %>% group_by(distc) %>% summarise(mean=mean(rsq),median=median(rsq))
chr4.tb1 <- chr4.tb %>% group_by(distc) %>% summarise(mean=mean(rsq),median=median(rsq))
chr5.tb1 <- chr5.tb %>% group_by(distc) %>% summarise(mean=mean(rsq),median=median(rsq))
chr6.tb1 <- chr6.tb %>% group_by(distc) %>% summarise(mean=mean(rsq),median=median(rsq))
head(chr2.pe1)
pe <- data.frame(chr2=chr2.pe1$mean, chr3=chr3.pe1$mean, chr4=chr4.pe1$mean, chr5=chr5.pe1$mean, chr6=chr6.pe1$mean)
tb <- data.frame(chr2=chr2.tb1$mean, chr3=chr3.tb1$mean, chr4=chr4.tb1$mean, chr5=chr5.tb1$mean, chr6=chr6.tb1$mean)
library(reshape2)
pem <- melt(pe)
head(pe)
head(pem)
p<-ggplot(pem, aes(x=variable, y=value, fill=variable)) +
  geom_violin(trim=FALSE)
ggsave("pe.all.chr.meanr2.pdf",p,height=8,width=8,units="cm",dpi=250)
p <- ggplot(pem, aes(x=variable, y=value, fill=variable)) + geom_violin(trim=FALSE)
ggsave("pe.all.chr.meanr2.pdf",p,height=8,width=8,units="cm",dpi=250)
p <- ggplot(pem, aes(x=variable, y=value, fill=variable)) + geom_violin()
ggsave("pe.all.chr.meanr2.pdf",p,height=8,width=8,units="cm",dpi=250)
p <- ggplot(pem, aes(x=variable, y=value, fill=variable)) + geom_boxplot() + stat_summary(fun.y=mean, geom="point", shape=23, size=4)
p <- ggplot(pem, aes(x=variable, y=value, fill=variable)) + geom_boxplot() + stat_summary(fun=mean, geom="point", shape=23, size=4)
ggsave("pe.all.chr.meanr2.pdf",p,height=8,width=8,units="cm",dpi=250)
p <- ggplot(pem, aes(x=variable, y=value, fill=variable)) + geom_boxplot() + classic_theme()
p <- ggplot(pem, aes(x=variable, y=value, fill=variable)) + geom_boxplot() + theme_classic()
ggsave("pe.all.chr.meanr2.pdf",p,height=8,width=8,units="cm",dpi=250)
colnames(pem) <- c("Chromosome", "LD(r2)")
p <- ggplot(pem, aes(x=variable, y=value, fill=variable)) + geom_boxplot() + theme_classic()
ggsave("pe.all.chr.meanr2.pdf",p,height=15,width=8,units="cm",dpi=250)
p <- ggplot(pem, aes(x=Chromosome, y=LD(r2), fill=Chromosome)) + geom_boxplot() + theme_classic()
ggsave("pe.all.chr.meanr2.pdf",p,height=15,width=8,units="cm",dpi=250)
colnames(pem) <- c("Chromosome", "r2")
head(pem)
p <- ggplot(pem, aes(x=Chromosome, y=r2, fill=Chromosome)) + geom_boxplot() + theme_classic()
ggsave("pe.all.chr.meanr2.pdf",p,height=15,width=8,units="cm",dpi=250)
p <- ggplot(pem, aes(x=Chromosome, y=r2, fill=Chromosome)) + geom_boxplot() + theme_classic()
ggsave("pe.all.chr.meanr2.pdf",p,height=12,width=10,units="cm",dpi=250)
colnames(pem) <- c("Chromosomes", "r2")
p <- ggplot(pem, aes(x=Chromosome, y=r2, fill=Chromosome)) + geom_boxplot() + theme_classic()
ggsave("pe.all.chr.meanr2.pdf",p,height=12,width=10,units="cm",dpi=250)
p <- ggplot(pem, aes(x=Chromosomes, y=r2, fill=Chromosomes)) + geom_boxplot() + theme_classic()
ggsave("pe.all.chr.meanr2.pdf",p,height=12,width=10,units="cm",dpi=250)
ggsave("pe.all.chr.meanr2.pdf",p,height=12,width=12,units="cm",dpi=250)
ggsave("pe.all.chr.meanr2.pdf",p,height=12,width=14,units="cm",dpi=250)
ggsave("pe.all.chr.meanr2.pdf",p,height=12,width=16,units="cm",dpi=250)
tbm <- melt(tb)
colnames(tbm) <- c("Chromosomes", "r2")
p2 <- ggplot(tbm, aes(x=Chromosomes, y=r2, fill=Chromosomes)) + geom_boxplot() + theme_classic()
ggsave("tb.all.chr.meanr2.pdf",p2,height=12,width=16,units="cm",dpi=250)
quit()
library(dplyr)
library(stringr)
library(ggplot2)
dir()
chr3.pe <- read.delim("peach.ld.summary",sep="",header=F,check.names=F,stringsAsFactors=F)
quit()
ls()
head(chr2.pe1)
chr2.pe1 <- chr2.pe1 %>% mutate(start=as.integer(str_extract(str_replace_all(distc,"[\\(\\)\\[\\]]",""),"^[0-9-e+.]+")), end=as.integer(str_extract(str_replace_all(distc,"[\\(\\)\\[\\]]",""),"[0-9-e+.]+$")), mid=start+((end-start)/2))
library(dplyr)
library(stringr)
library(ggplot2)
chr2.pe1 <- chr2.pe1 %>% mutate(start=as.integer(str_extract(str_replace_all(distc,"[\\(\\)\\[\\]]",""),"^[0-9-e+.]+")), end=as.integer(str_extract(str_replace_all(distc,"[\\(\\)\\[\\]]",""),"[0-9-e+.]+$")), mid=start+((end-start)/2))
chr2.tb1 <- chr2.tb1 %>% mutate(start=as.integer(str_extract(str_replace_all(distc,"[\\(\\)\\[\\]]",""),"^[0-9-e+.]+")), end=as.integer(str_extract(str_replace_all(distc,"[\\(\\)\\[\\]]",""),"[0-9-e+.]+$")), mid=start+((end-start)/2))
ls()
rm(chr2.pe)
rm(chr2.pe1,chr2.tb)
rm(chr2.tb1,chr3.pe,chr3.pe1,chr3.tb,chr3.tb1,chr4.pe,chr4.pe1,chr4.tb,chr4.tb1,chr5.pe,chr5.pe1,chr5.tb,chr5.tb1,chr6.pe,chr6.pe1,chr6.tb,chr6.tb1)
ls()
dir()
dir("LD_decay_chr2")
chr2.pe.gc <- read.delim("peach.gc-thin2.ld.summary",sep="",header=F,check.names=F,stringsAsFactors=F)
chr2.pe.gc <- read.delim("LD_decay_chr2/peach.gc-thin2.ld.summary",sep="",header=F,check.names=F,stringsAsFactors=F)
chr2.pe.it <- read.delim("LD_decay_chr2/peach.it-thin2.ld.summary",sep="",header=F,check.names=F,stringsAsFactors=F)
chr2.tb.it <- read.delim("LD_decay_chr2/tobacco.gc-thin2.ld.summary",sep="",header=F,check.names=F,stringsAsFactors=F)
chr2.tb.it <- read.delim("LD_decay_chr2/tobacco.it-thin2.ld.summary",sep="",header=F,check.names=F,stringsAsFactors=F)
chr2.tb.gc <- read.delim("LD_decay_chr2/tobacco.gc-thin2.ld.summary",sep="",header=F,check.names=F,stringsAsFactors=F)
chr4.pe.gc <- read.delim("LD_decay_chr4/peach.gc-thin2.ld.summary",sep="",header=F,check.names=F,stringsAsFactors=F)
dir("LD_decay_chr4/")
quit()
ls()
chr4.pe.gc <- read.delim("LD_decay_chr4/peach.gc-thin2.ld.summary",sep="",header=F,check.names=F,stringsAsFactors=F)
chr4.pe.it <- read.delim("LD_decay_chr4/peach.it-thin2.ld.summary",sep="",header=F,check.names=F,stringsAsFactors=F)
chr4.tb.it <- read.delim("LD_decay_chr4/tobacco.it-thin2.ld.summary",sep="",header=F,check.names=F,stringsAsFactors=F)
chr4.tb.gc <- read.delim("LD_decay_chr4/tobacco.gc-thin2.ld.summary",sep="",header=F,check.names=F,stringsAsFactors=F)
chr5.pe.gc <- read.delim("LD_decay_chr5/peach.gc-thin2.ld.summary",sep="",header=F,check.names=F,stringsAsFactors=F)
chr5.pe.it <- read.delim("LD_decay_chr5/peach.it-thin2.ld.summary",sep="",header=F,check.names=F,stringsAsFactors=F)
chr5.tb.it <- read.delim("LD_decay_chr5/tobacco.it-thin2.ld.summary",sep="",header=F,check.names=F,stringsAsFactors=F)
chr5.tb.it <- read.delim("LD_decay_chr5/tobacco.it-thin2.ld.summary",sep="",header=F,check.names=F,stringsAsFactors=F)
chr5.tb.gc <- read.delim("LD_decay_chr5/tobacco.gc-thin2.ld.summary",sep="",header=F,check.names=F,stringsAsFactors=F)
chr5.pe.gc <- read.delim("LD_decay_chr5/peach.gc-thin2.ld.summary",sep="",header=F,check.names=F,stringsAsFactors=F)
chr6.pe.gc <- read.delim("LD_decay_chr6/peach.gc-thin2.ld.summary",sep="",header=F,check.names=F,stringsAsFactors=F)
chr6.pe.it <- read.delim("LD_decay_chr6/peach.it-thin2.ld.summary",sep="",header=F,check.names=F,stringsAsFactors=F)
chr6.tb.it <- read.delim("LD_decay_chr6/tobacco.it-thin2.ld.summary",sep="",header=F,check.names=F,stringsAsFactors=F)
chr6.tb.gc <- read.delim("LD_decay_chr6/tobacco.gc-thin2.ld.summary",sep="",header=F,check.names=F,stringsAsFactors=F)
chr3.pe.gc <- read.delim("country_correct/peach.gc-thin2.ld.summary",sep="",header=F,check.names=F,stringsAsFactors=F)
chr3.pe.gc <- read.delim("country_correct/peach.greece-thin2.ld.summary",sep="",header=F,check.names=F,stringsAsFactors=F)
chr3.pe.gc <- read.delim("country_correct/peach.greece.thin2.ld.summary",sep="",header=F,check.names=F,stringsAsFactors=F)
chr3.pe.it <- read.delim("country_correct/peach.italy.thin2.ld.summary",sep="",header=F,check.names=F,stringsAsFactors=F)
chr3.tb.it <- read.delim("country_correct/tobacco.italy.thin2.ld.summary",sep="",header=F,check.names=F,stringsAsFactors=F)
chr3.tb.gc <- read.delim("country_correct/tobacco.greece.thin2.ld.summary",sep="",header=F,check.names=F,stringsAsFactors=F)
ls()
chr2.pe.gc$distc <- cut(chr2.pe.gc$dist,breaks=seq(from=min(chr2.pe.gc$dist)-1,to=max(chr2.pe.gc$dist)+1,by=100000))
colnames(chr2.pe.gc) <- c("dist","rsq")
colnames(chr2.pe.it) <- c("dist","rsq")
colnames(chr2.tb.it) <- c("dist","rsq")
colnames(chr2.tb.gc) <- c("dist","rsq")
colnames(chr3.pe.gc) <- c("dist","rsq")
colnames(chr3.pe.it) <- c("dist","rsq")
colnames(chr3.tb.it) <- c("dist","rsq")
colnames(chr3.tb.gc) <- c("dist","rsq")
colnames(chr4.pe.gc) <- c("dist","rsq")
colnames(chr4.pe.it) <- c("dist","rsq")
colnames(chr4.tb.it) <- c("dist","rsq")
colnames(chr4.tb.gc) <- c("dist","rsq")
colnames(chr5.pe.gc) <- c("dist","rsq")
colnames(chr5.pe.it) <- c("dist","rsq")
colnames(chr5.tb.it) <- c("dist","rsq")
colnames(chr5.tb.gc) <- c("dist","rsq")
colnames(chr6.pe.gc) <- c("dist","rsq")
colnames(chr6.pe.it) <- c("dist","rsq")
colnames(chr6.tb.it) <- c("dist","rsq")
colnames(chr6.tb.gc) <- c("dist","rsq")
chr2.pe.gc$distc <- cut(chr2.pe.gc$dist,breaks=seq(from=min(chr2.pe.gc$dist)-1,to=max(chr2.pe.gc$dist)+1,by=100000))
chr2.pe.it$distc <- cut(chr2.pe.it$dist,breaks=seq(from=min(chr2.pe.it$dist)-1,to=max(chr2.pe.it$dist)+1,by=100000))
chr2.tb.it$distc <- cut(chr2.tb.it$dist,breaks=seq(from=min(chr2.tb.it$dist)-1,to=max(chr2.tb.it$dist)+1,by=100000))
chr2.tb.gc$distc <- cut(chr2.tb.gc$dist,breaks=seq(from=min(chr2.tb.gc$dist)-1,to=max(chr2.tb.gc$dist)+1,by=100000))
chr3.pe.gc$distc <- cut(chr3.pe.gc$dist,breaks=seq(from=min(chr3.pe.gc$dist)-1,to=max(chr3.pe.gc$dist)+1,by=100000))
chr3.pe.it$distc <- cut(chr3.pe.it$dist,breaks=seq(from=min(chr3.pe.it$dist)-1,to=max(chr3.pe.it$dist)+1,by=100000))
chr3.tb.it$distc <- cut(chr3.tb.it$dist,breaks=seq(from=min(chr3.tb.it$dist)-1,to=max(chr3.tb.it$dist)+1,by=100000))
chr3.tb.gc$distc <- cut(chr3.tb.gc$dist,breaks=seq(from=min(chr3.tb.gc$dist)-1,to=max(chr3.tb.gc$dist)+1,by=100000))
chr4.pe.gc$distc <- cut(chr4.pe.gc$dist,breaks=seq(from=min(chr4.pe.gc$dist)-1,to=max(chr4.pe.gc$dist)+1,by=100000))
chr4.pe.it$distc <- cut(chr4.pe.it$dist,breaks=seq(from=min(chr4.pe.it$dist)-1,to=max(chr4.pe.it$dist)+1,by=100000))
chr4.tb.it$distc <- cut(chr4.tb.it$dist,breaks=seq(from=min(chr4.tb.it$dist)-1,to=max(chr4.tb.it$dist)+1,by=100000))
chr4.tb.gc$distc <- cut(chr4.tb.gc$dist,breaks=seq(from=min(chr4.tb.gc$dist)-1,to=max(chr4.tb.gc$dist)+1,by=100000))
chr5.pe.gc$distc <- cut(chr5.pe.gc$dist,breaks=seq(from=min(chr5.pe.gc$dist)-1,to=max(chr5.pe.gc$dist)+1,by=100000))
chr5.pe.it$distc <- cut(chr5.pe.it$dist,breaks=seq(from=min(chr5.pe.it$dist)-1,to=max(chr5.pe.it$dist)+1,by=100000))
chr5.tb.it$distc <- cut(chr5.tb.it$dist,breaks=seq(from=min(chr5.tb.it$dist)-1,to=max(chr5.tb.it$dist)+1,by=100000))
chr5.tb.gc$distc <- cut(chr5.tb.gc$dist,breaks=seq(from=min(chr5.tb.gc$dist)-1,to=max(chr5.tb.gc$dist)+1,by=100000))
chr6.pe.gc$distc <- cut(chr6.pe.gc$dist,breaks=seq(from=min(chr6.pe.gc$dist)-1,to=max(chr6.pe.gc$dist)+1,by=100000))
chr6.pe.it$distc <- cut(chr6.pe.it$dist,breaks=seq(from=min(chr6.pe.it$dist)-1,to=max(chr6.pe.it$dist)+1,by=100000))
chr6.tb.it$distc <- cut(chr6.tb.it$dist,breaks=seq(from=min(chr6.tb.it$dist)-1,to=max(chr6.tb.it$dist)+1,by=100000))
chr6.tb.gc$distc <- cut(chr6.tb.gc$dist,breaks=seq(from=min(chr6.tb.gc$dist)-1,to=max(chr6.tb.gc$dist)+1,by=100000))
chr2.pe.gc1 <- chr3.pe.gc %>% group_by(distc) %>% summarise(mean=mean(rsq),median=median(rsq))
library(dplyr)
library(stringr)
library(ggplot2)
chr2.pe.gc1 <- chr3.pe.gc %>% group_by(distc) %>% summarise(mean=mean(rsq),median=median(rsq))
chr2.pe.it1 <- chr3.pe.it %>% group_by(distc) %>% summarise(mean=mean(rsq),median=median(rsq))
chr2.tb.gc1 <- chr3.tb.gc %>% group_by(distc) %>% summarise(mean=mean(rsq),median=median(rsq))
chr2.tb.it1 <- chr3.tb.it %>% group_by(distc) %>% summarise(mean=mean(rsq),median=median(rsq))
chr3.pe.gc1 <- chr3.pe.gc %>% group_by(distc) %>% summarise(mean=mean(rsq),median=median(rsq))
chr3.pe.it1 <- chr3.pe.it %>% group_by(distc) %>% summarise(mean=mean(rsq),median=median(rsq))
chr3.tb.gc1 <- chr3.tb.gc %>% group_by(distc) %>% summarise(mean=mean(rsq),median=median(rsq))
chr3.tb.it1 <- chr3.tb.it %>% group_by(distc) %>% summarise(mean=mean(rsq),median=median(rsq))
chr4.pe.gc1 <- chr3.pe.gc %>% group_by(distc) %>% summarise(mean=mean(rsq),median=median(rsq))
chr4.pe.it1 <- chr3.pe.it %>% group_by(distc) %>% summarise(mean=mean(rsq),median=median(rsq))
chr4.tb.gc1 <- chr3.tb.gc %>% group_by(distc) %>% summarise(mean=mean(rsq),median=median(rsq))
chr4.tb.it1 <- chr3.tb.it %>% group_by(distc) %>% summarise(mean=mean(rsq),median=median(rsq))
chr5.pe.gc1 <- chr3.pe.gc %>% group_by(distc) %>% summarise(mean=mean(rsq),median=median(rsq))
chr5.pe.it1 <- chr3.pe.it %>% group_by(distc) %>% summarise(mean=mean(rsq),median=median(rsq))
chr5.tb.gc1 <- chr3.tb.gc %>% group_by(distc) %>% summarise(mean=mean(rsq),median=median(rsq))
chr5.tb.it1 <- chr3.tb.it %>% group_by(distc) %>% summarise(mean=mean(rsq),median=median(rsq))
chr6.pe.gc1 <- chr3.pe.gc %>% group_by(distc) %>% summarise(mean=mean(rsq),median=median(rsq))
chr6.pe.it1 <- chr3.pe.it %>% group_by(distc) %>% summarise(mean=mean(rsq),median=median(rsq))
chr6.tb.gc1 <- chr3.tb.gc %>% group_by(distc) %>% summarise(mean=mean(rsq),median=median(rsq))
chr6.tb.it1 <- chr3.tb.it %>% group_by(distc) %>% summarise(mean=mean(rsq),median=median(rsq))
chr2.pe.gc1 <- chr2.pe.gc %>% group_by(distc) %>% summarise(mean=mean(rsq),median=median(rsq))
chr2.pe.it1 <- chr2.pe.it %>% group_by(distc) %>% summarise(mean=mean(rsq),median=median(rsq))
chr2.tb.gc1 <- chr2.tb.gc %>% group_by(distc) %>% summarise(mean=mean(rsq),median=median(rsq))
chr2.tb.it1 <- chr2.tb.it %>% group_by(distc) %>% summarise(mean=mean(rsq),median=median(rsq))
chr4.pe.gc1 <- chr4.pe.gc %>% group_by(distc) %>% summarise(mean=mean(rsq),median=median(rsq))
chr4.pe.it1 <- chr4.pe.it %>% group_by(distc) %>% summarise(mean=mean(rsq),median=median(rsq))
chr4.tb.gc1 <- chr4.tb.gc %>% group_by(distc) %>% summarise(mean=mean(rsq),median=median(rsq))
chr4.tb.it1 <- chr4.tb.it %>% group_by(distc) %>% summarise(mean=mean(rsq),median=median(rsq))
chr5.pe.gc1 <- chr5.pe.gc %>% group_by(distc) %>% summarise(mean=mean(rsq),median=median(rsq))
chr5.pe.it1 <- chr5.pe.it %>% group_by(distc) %>% summarise(mean=mean(rsq),median=median(rsq))
chr5.tb.gc1 <- chr5.tb.gc %>% group_by(distc) %>% summarise(mean=mean(rsq),median=median(rsq))
chr5.tb.it1 <- chr5.tb.it %>% group_by(distc) %>% summarise(mean=mean(rsq),median=median(rsq))
chr6.pe.gc1 <- chr6.pe.gc %>% group_by(distc) %>% summarise(mean=mean(rsq),median=median(rsq))
chr6.pe.it1 <- chr6.pe.it %>% group_by(distc) %>% summarise(mean=mean(rsq),median=median(rsq))
chr6.tb.gc1 <- chr6.tb.gc %>% group_by(distc) %>% summarise(mean=mean(rsq),median=median(rsq))
chr6.tb.it1 <- chr6.tb.it %>% group_by(distc) %>% summarise(mean=mean(rsq),median=median(rsq))
chr2.pe.gc1 <- chr2.pe.gc1 %>% mutate(start=as.integer(str_extract(str_replace_all(distc,"[\\(\\)\\[\\]]",""),"^[0-9-e+.]+")), end=as.integer(str_extract(str_replace_all(distc,"[\\(\\)\\[\\]]",""),"[0-9-e+.]+$")), mid=start+((end-start)/2))
chr2.pe.it1 <- chr2.pe.it1 %>% mutate(start=as.integer(str_extract(str_replace_all(distc,"[\\(\\)\\[\\]]",""),"^[0-9-e+.]+")), end=as.integer(str_extract(str_replace_all(distc,"[\\(\\)\\[\\]]",""),"[0-9-e+.]+$")), mid=start+((end-start)/2))
chr2.tb.gc1 <- chr2.tb.gc1 %>% mutate(start=as.integer(str_extract(str_replace_all(distc,"[\\(\\)\\[\\]]",""),"^[0-9-e+.]+")), end=as.integer(str_extract(str_replace_all(distc,"[\\(\\)\\[\\]]",""),"[0-9-e+.]+$")), mid=start+((end-start)/2))
chr2.tb.it1 <- chr2.tb.it1 %>% mutate(start=as.integer(str_extract(str_replace_all(distc,"[\\(\\)\\[\\]]",""),"^[0-9-e+.]+")), end=as.integer(str_extract(str_replace_all(distc,"[\\(\\)\\[\\]]",""),"[0-9-e+.]+$")), mid=start+((end-start)/2))
chr3.pe.gc1 <- chr3.pe.gc1 %>% mutate(start=as.integer(str_extract(str_replace_all(distc,"[\\(\\)\\[\\]]",""),"^[0-9-e+.]+")), end=as.integer(str_extract(str_replace_all(distc,"[\\(\\)\\[\\]]",""),"[0-9-e+.]+$")), mid=start+((end-start)/2))
chr3.pe.it1 <- chr3.pe.it1 %>% mutate(start=as.integer(str_extract(str_replace_all(distc,"[\\(\\)\\[\\]]",""),"^[0-9-e+.]+")), end=as.integer(str_extract(str_replace_all(distc,"[\\(\\)\\[\\]]",""),"[0-9-e+.]+$")), mid=start+((end-start)/2))
chr3.tb.gc1 <- chr3.tb.gc1 %>% mutate(start=as.integer(str_extract(str_replace_all(distc,"[\\(\\)\\[\\]]",""),"^[0-9-e+.]+")), end=as.integer(str_extract(str_replace_all(distc,"[\\(\\)\\[\\]]",""),"[0-9-e+.]+$")), mid=start+((end-start)/2))
chr3.tb.it1 <- chr3.tb.it1 %>% mutate(start=as.integer(str_extract(str_replace_all(distc,"[\\(\\)\\[\\]]",""),"^[0-9-e+.]+")), end=as.integer(str_extract(str_replace_all(distc,"[\\(\\)\\[\\]]",""),"[0-9-e+.]+$")), mid=start+((end-start)/2))
chr4.pe.gc1 <- chr4.pe.gc1 %>% mutate(start=as.integer(str_extract(str_replace_all(distc,"[\\(\\)\\[\\]]",""),"^[0-9-e+.]+")), end=as.integer(str_extract(str_replace_all(distc,"[\\(\\)\\[\\]]",""),"[0-9-e+.]+$")), mid=start+((end-start)/2))
chr4.pe.it1 <- chr4.pe.it1 %>% mutate(start=as.integer(str_extract(str_replace_all(distc,"[\\(\\)\\[\\]]",""),"^[0-9-e+.]+")), end=as.integer(str_extract(str_replace_all(distc,"[\\(\\)\\[\\]]",""),"[0-9-e+.]+$")), mid=start+((end-start)/2))
chr4.tb.gc1 <- chr4.tb.gc1 %>% mutate(start=as.integer(str_extract(str_replace_all(distc,"[\\(\\)\\[\\]]",""),"^[0-9-e+.]+")), end=as.integer(str_extract(str_replace_all(distc,"[\\(\\)\\[\\]]",""),"[0-9-e+.]+$")), mid=start+((end-start)/2))
chr4.tb.it1 <- chr4.tb.it1 %>% mutate(start=as.integer(str_extract(str_replace_all(distc,"[\\(\\)\\[\\]]",""),"^[0-9-e+.]+")), end=as.integer(str_extract(str_replace_all(distc,"[\\(\\)\\[\\]]",""),"[0-9-e+.]+$")), mid=start+((end-start)/2))
chr5.pe.gc1 <- chr5.pe.gc1 %>% mutate(start=as.integer(str_extract(str_replace_all(distc,"[\\(\\)\\[\\]]",""),"^[0-9-e+.]+")), end=as.integer(str_extract(str_replace_all(distc,"[\\(\\)\\[\\]]",""),"[0-9-e+.]+$")), mid=start+((end-start)/2))
chr5.pe.it1 <- chr5.pe.it1 %>% mutate(start=as.integer(str_extract(str_replace_all(distc,"[\\(\\)\\[\\]]",""),"^[0-9-e+.]+")), end=as.integer(str_extract(str_replace_all(distc,"[\\(\\)\\[\\]]",""),"[0-9-e+.]+$")), mid=start+((end-start)/2))
chr5.tb.gc1 <- chr5.tb.gc1 %>% mutate(start=as.integer(str_extract(str_replace_all(distc,"[\\(\\)\\[\\]]",""),"^[0-9-e+.]+")), end=as.integer(str_extract(str_replace_all(distc,"[\\(\\)\\[\\]]",""),"[0-9-e+.]+$")), mid=start+((end-start)/2))
chr5.tb.it1 <- chr5.tb.it1 %>% mutate(start=as.integer(str_extract(str_replace_all(distc,"[\\(\\)\\[\\]]",""),"^[0-9-e+.]+")), end=as.integer(str_extract(str_replace_all(distc,"[\\(\\)\\[\\]]",""),"[0-9-e+.]+$")), mid=start+((end-start)/2))
chr6.pe.gc1 <- chr6.pe.gc1 %>% mutate(start=as.integer(str_extract(str_replace_all(distc,"[\\(\\)\\[\\]]",""),"^[0-9-e+.]+")), end=as.integer(str_extract(str_replace_all(distc,"[\\(\\)\\[\\]]",""),"[0-9-e+.]+$")), mid=start+((end-start)/2))
chr6.pe.it1 <- chr6.pe.it1 %>% mutate(start=as.integer(str_extract(str_replace_all(distc,"[\\(\\)\\[\\]]",""),"^[0-9-e+.]+")), end=as.integer(str_extract(str_replace_all(distc,"[\\(\\)\\[\\]]",""),"[0-9-e+.]+$")), mid=start+((end-start)/2))
chr6.tb.gc1 <- chr6.tb.gc1 %>% mutate(start=as.integer(str_extract(str_replace_all(distc,"[\\(\\)\\[\\]]",""),"^[0-9-e+.]+")), end=as.integer(str_extract(str_replace_all(distc,"[\\(\\)\\[\\]]",""),"[0-9-e+.]+$")), mid=start+((end-start)/2))
chr6.tb.it1 <- chr6.tb.it1 %>% mutate(start=as.integer(str_extract(str_replace_all(distc,"[\\(\\)\\[\\]]",""),"^[0-9-e+.]+")), end=as.integer(str_extract(str_replace_all(distc,"[\\(\\)\\[\\]]",""),"[0-9-e+.]+$")), mid=start+((end-start)/2))
head(chr6.tb.it1)
ls()
p1 <- ggplot()+ geom_point(data=chr2.pe.gc1,aes(x=start,y=mean),size=0.4,colour="brown3")+geom_line(data=dfr1,aes(x=start,y=mean),size=0.3,alpha=0.5,colour="brown3") + geom_point(data=chr3.pe.gc1,aes(x=start,y=mean),size=0.4,colour="darkorange3")+geom_line(data=dfr1,aes(x=start,y=mean),size=0.3,alpha=0.5,colour="darkorange3") + geom_point(data=chr4.pe.gc1,aes(x=start,y=mean),size=0.4,colour="cyan3")+geom_line(data=dfr1,aes(x=start,y=mean),size=0.3,alpha=0.5,colour="cyan3") + geom_point(data=chr5.pe.gc1,aes(x=start,y=mean),size=0.4,colour="gold3")+geom_line(data=dfr1,aes(x=start,y=mean),size=0.3,alpha=0.5,colour="gold3") + geom_point(data=chr6.pe.gc1,aes(x=start,y=mean),size=0.4,colour="olivedrab3")+geom_line(data=dfr1,aes(x=start,y=mean),size=0.3,alpha=0.5,colour="olivedrab3")+labs(x="Distance (Megabases)",y=expression(LD~(r^{2})))+scale_x_continuous(breaks=c(0,2*10^6,4*10^6,6*10^6,8*10^6),labels=c("0","2","4","6","8"))+theme_bw()
p1 <- ggplot()+ geom_point(data=chr2.pe.gc1,aes(x=start,y=mean),size=0.4,colour="brown3")+geom_line(data=chr2.pe.gc1,aes(x=start,y=mean),size=0.3,alpha=0.5,colour="brown3") + geom_point(data=chr3.pe.gc1,aes(x=start,y=mean),size=0.4,colour="darkorange3")+geom_line(data=chr3.pe.gc,aes(x=start,y=mean),size=0.3,alpha=0.5,colour="darkorange3") + geom_point(data=chr4.pe.gc1,aes(x=start,y=mean),size=0.4,colour="cyan3")+geom_line(data=chr4.pe.gc1,aes(x=start,y=mean),size=0.3,alpha=0.5,colour="cyan3") + geom_point(data=chr5.pe.gc1,aes(x=start,y=mean),size=0.4,colour="gold3")+geom_line(data=chr5.pe.gc1,aes(x=start,y=mean),size=0.3,alpha=0.5,colour="gold3") + geom_point(data=chr6.pe.gc1,aes(x=start,y=mean),size=0.4,colour="olivedrab3")+geom_line(data=chr6.pe.gc,aes(x=start,y=mean),size=0.3,alpha=0.5,colour="olivedrab3")+labs(x="Distance (Megabases)",y=expression(LD~(r^{2})))+scale_x_continuous(breaks=c(0,2*10^6,4*10^6,6*10^6,8*10^6),labels=c("0","2","4","6","8"))+theme_bw()
ggsave("all.chr.pe.gc.pdf",p1,height=8,width=8,units="cm",dpi=250)
p1 <- ggplot() + geom_point(data = chr2.pe.gc1,aes(x = start,y = mean),size = 0.4,colour = "brown3") + geom_line(data=chr2.pe.gc1,aes(x = start, y = mean),size=0.3,alpha=0.5,colour="brown3") + geom_point(data=chr3.pe.gc1, aes(x = start,y = mean),size=0.4,colour="darkorange3") + geom_line(data=chr3.pe.gc,aes(x = start,y = mean), size=0.3,alpha=0.5,colour="darkorange3") + geom_point(data=chr4.pe.gc1,aes(x = start,y = mean),size=0.4,colour="cyan3") + geom_line(data=chr4.pe.gc1, aes(x = start,y = mean),size=0.3,alpha=0.5,colour="cyan3") + geom_point(data=chr5.pe.gc1,aes(x = start,y = mean),size=0.4,colour="gold3") + geom_line(data = chr5.pe.gc1,aes(x = start,y = mean),size=0.3,alpha=0.5,colour="gold3") + geom_point(data = chr6.pe.gc1,aes(x = start, y = mean),size=0.4,colour="olivedrab3") + geom_line(data = chr6.pe.gc,aes(x = start,y = mean),size=0.3,alpha=0.5,colour="olivedrab3")+labs(x="Distance (Megabases)",y=expression(LD~(r^{2})))+scale_x_continuous(breaks=c(0,2*10^6,4*10^6,6*10^6,8*10^6),labels=c("0","2","4","6","8"))+theme_bw()
ggsave("all.chr.pe.gc.pdf",p1,height=8,width=8,units="cm",dpi=250)
head(chr2.pe.gc1)
head(chr3.pe.gc1)
head(chr4.pe.gc1)
head(chr5.pe.gc1)
head(chr6.pe.gc1)
p1
ggplot() + geom_point(data = chr2.pe.gc1, aes(x = start, y = mean), size = 0.4, colour = "brown3") + geom_line(data = chr2.pe.gc1, aes(x = start, y = mean), size = 0.3, alpha = 0.5, colour = "brown3") + geom_point(data = chr3.pe.gc1, aes(x = start, y = mean), size = 0.4, colour = "darkorange3") + geom_line(data = chr3.pe.gc, aes(x = start, y = mean), size = 0.3, alpha = 0.5, colour = "darkorange3") + geom_point(data = chr4.pe.gc1, aes(x = start, y = mean), size = 0.4, colour = "cyan3") + geom_line(data = chr4.pe.gc1, aes(x = start, y = mean), size = 0.3, alpha = 0.5, colour = "cyan3") + geom_point(data = chr5.pe.gc1, aes(x = start, y = mean), size = 0.4, colour = "gold3") + geom_line(data = chr5.pe.gc1, aes(x = start, y = mean), size = 0.3, alpha = 0.5, colour = "gold3") + geom_point(data = chr6.pe.gc1, aes(x = start, y = mean), size = 0.4, colour = "olivedrab3") + geom_line(data = chr6.pe.gc, aes(x = start, y = mean), size = 0.3, alpha = 0.5, colour = "olivedrab3") + labs(x="Distance (Megabases)", y=expression(LD~(r^{2}))) + scale_x_continuous(breaks=c(0,2*10^6,4*10^6,6*10^6,8*10^6), labels=c("0","2","4","6","8")) + theme_bw()
ggplot() + geom_point(data = chr2.pe.gc1, aes(x = chr2.pe.gc1$start, y = chr2.pe.gc1$mean), size = 0.4, colour = "brown3") + geom_line(data = chr2.pe.gc1, aes(x = chr2.pe.gc$start, y = chr2.pe.gc$mean), size = 0.3, alpha = 0.5, colour = "brown3") + geom_point(data = chr3.pe.gc1, aes(x = chr3.pe.gc1$start, y = chr3.pe.gc1$mean), size = 0.4, colour = "darkorange3") + geom_line(data = chr3.pe.gc, aes(x = chr3.pe.gc1$start, y = chr3.pe.gc1$mean), size = 0.3, alpha = 0.5, colour = "darkorange3") + geom_point(data = chr4.pe.gc1, aes(x = chr4.pe.gc1$start, y = chr4.pe.gc1$mean), size = 0.4, colour = "cyan3") + geom_line(data = chr4.pe.gc1, aes(x = chr4.pe.gc1$start, y = chr4.pe.gc1$mean), size = 0.3, alpha = 0.5, colour = "cyan3") + geom_point(data = chr5.pe.gc1, aes(x = chr5.pe.gc1$start, y = chr5.pe.gc1$mean), size = 0.4, colour = "gold3") + geom_line(data = chr5.pe.gc1, aes(x = chr5.pe.gc1$start, y = chr5.pe.gc1$mean), size = 0.3, alpha = 0.5, colour = "gold3") + geom_point(data = chr6.pe.gc1, aes(x = chr6.pe.gc1$start, y = chr6.pe.gc1$mean), size = 0.4, colour = "olivedrab3") + geom_line(data = chr6.pe.gc, aes(x = chr6.pe.gc1$start, y = chr6.pe.gc1$mean), size = 0.3, alpha = 0.5, colour = "olivedrab3") + labs(x="Distance (Megabases)", y=expression(LD~(r^{2}))) + scale_x_continuous(breaks=c(0,2*10^6,4*10^6,6*10^6,8*10^6), labels=c("0","2","4","6","8")) + theme_bw()
ggplot() + geom_line(data=chr2.pe.gc1, aes(x=start, y=mean), size = 0.3, alpha = 0.5, colour = "brown3") + geom_point(data=chr3.pe.gc1, aes(x=start, y=mean), size = 0.4, colour = "darkorange3") + geom_line(data=chr3.pe.gc, aes(x=start, y=mean), size = 0.3, alpha = 0.5, colour = "darkorange3") + geom_line(data=chr4.pe.gc1, aes(x=start, y=mean), size = 0.3, alpha = 0.5, colour = "cyan3") + geom_line(data=chr5.pe.gc1, aes(x=start, y=mean), size = 0.3, alpha = 0.5, colour = "gold3") + geom_line(data=chr6.pe.gc, aes(x=start, y=mean), size = 0.3, alpha = 0.5, colour = "olivedrab3") + labs(x="Distance (Megabases)", y=expression(LD~(r^{2}))) + scale_x_continuous(breaks=c(0,2*10^6,4*10^6,6*10^6,8*10^6), labels=c("0","2","4","6","8")) + theme_bw()
ggplot() + geom_point(data = chr2.pe.gc1, aes(x = start, y = mean), size = 0.4, colour = "brown3") + geom_line(data = chr2.pe.gc1, aes(x = start, y = mean), size = 0.3, alpha = 0.5, colour = "brown3") + geom_point(data = chr3.pe.gc1, aes(x = start, y = mean), size = 0.4, colour = "darkorange3") + geom_line(data = chr3.pe.gc1, aes(x = start, y = mean), size = 0.3, alpha = 0.5, colour = "darkorange3") + geom_point(data = chr4.pe.gc1, aes(x = start, y = mean), size = 0.4, colour = "cyan3") + geom_line(data = chr4.pe.gc1, aes(x = start, y = mean), size = 0.3, alpha = 0.5, colour = "cyan3") + geom_point(data = chr5.pe.gc1, aes(x = start, y = mean), size = 0.4, colour = "gold3") + geom_line(data = chr5.pe.gc1, aes(x = start, y = mean), size = 0.3, alpha = 0.5, colour = "gold3") + geom_point(data = chr6.pe.gc1, aes(x = start, y = mean), size = 0.4, colour = "olivedrab3") + geom_line(data = chr6.pe.gc1, aes(x = start, y = mean), size = 0.3, alpha = 0.5, colour = "olivedrab3") + labs(x="Distance (Megabases)", y=expression(LD~(r^{2}))) + scale_x_continuous(breaks=c(0,2*10^6,4*10^6,6*10^6,8*10^6), labels=c("0","2","4","6","8")) + theme_bw()
ggplot() + geom_point(data = chr2.pe.gc1, aes(x = start, y = mean), size = 0.4, colour = "brown3") + geom_line(data = chr2.pe.gc1, aes(x = start, y = mean), size = 0.3, alpha = 0.5, colour = "brown3") + geom_point(data = chr3.pe.gc1, aes(x = start, y = mean), size = 0.4, colour = "darkorange3") + geom_line(data = chr3.pe.gc1, aes(x = start, y = mean), size = 0.3, alpha = 0.5, colour = "darkorange3") + geom_point(data = chr4.pe.gc1, aes(x = start, y = mean), size = 0.4, colour = "cyan3") + geom_line(data = chr4.pe.gc1, aes(x = start, y = mean), size = 0.3, alpha = 0.5, colour = "cyan3") + geom_point(data = chr5.pe.gc1, aes(x = start, y = mean), size = 0.4, colour = "gold3") + geom_line(data = chr5.pe.gc1, aes(x = start, y = mean), size = 0.3, alpha = 0.5, colour = "gold3") + geom_point(data = chr6.pe.gc1, aes(x = start, y = mean), size = 0.4, colour = "olivedrab3") + geom_line(data = chr6.pe.gc1, aes(x = start, y = mean), size = 0.3, alpha = 0.5, colour = "olivedrab3") + labs(x="Distance (Megabases)", y=expression(LD~(r^{2}))) + scale_x_continuous(breaks=c(0,2*10^6,4*10^6,6*10^6,8*10^6), labels=c("0","2","4","6","8")) + theme_bw()
ggplot() + geom_point(data = chr2.pe.gc1, aes(x = start, y = mean), size = 0.4, colour = "brown3") + geom_line(data = chr2.pe.gc1, aes(x = start, y = mean), size = 0.3, alpha = 0.5, colour = "brown3") + geom_point(data = chr3.pe.gc1, aes(x = start, y = mean), size = 0.4, colour = "magenta3") + geom_line(data = chr3.pe.gc1, aes(x = start, y = mean), size = 0.3, alpha = 0.5, colour = "magenta3") + geom_point(data = chr4.pe.gc1, aes(x = start, y = mean), size = 0.4, colour = "cyan3") + geom_line(data = chr4.pe.gc1, aes(x = start, y = mean), size = 0.3, alpha = 0.5, colour = "cyan3") + geom_point(data = chr5.pe.gc1, aes(x = start, y = mean), size = 0.4, colour = "gold3") + geom_line(data = chr5.pe.gc1, aes(x = start, y = mean), size = 0.3, alpha = 0.5, colour = "gold3") + geom_point(data = chr6.pe.gc1, aes(x = start, y = mean), size = 0.4, colour = "olivedrab3") + geom_line(data = chr6.pe.gc1, aes(x = start, y = mean), size = 0.3, alpha = 0.5, colour = "olivedrab3") + labs(x="Distance (Megabases)", y=expression(LD~(r^{2}))) + scale_x_continuous(breaks=c(0,2*10^6,4*10^6,6*10^6,8*10^6), labels=c("0","2","4","6","8")) + theme_bw()
p1 <- ggplot() + geom_point(data = chr2.pe.gc1, aes(x = start, y = mean), size = 0.4, colour = "brown3") + geom_line(data = chr2.pe.gc1, aes(x = start, y = mean), size = 0.3, alpha = 0.5, colour = "brown3") + geom_point(data = chr3.pe.gc1, aes(x = start, y = mean), size = 0.4, colour = "magenta3") + geom_line(data = chr3.pe.gc1, aes(x = start, y = mean), size = 0.3, alpha = 0.5, colour = "magenta3") + geom_point(data = chr4.pe.gc1, aes(x = start, y = mean), size = 0.4, colour = "cyan3") + geom_line(data = chr4.pe.gc1, aes(x = start, y = mean), size = 0.3, alpha = 0.5, colour = "cyan3") + geom_point(data = chr5.pe.gc1, aes(x = start, y = mean), size = 0.4, colour = "gold3") + geom_line(data = chr5.pe.gc1, aes(x = start, y = mean), size = 0.3, alpha = 0.5, colour = "gold3") + geom_point(data = chr6.pe.gc1, aes(x = start, y = mean), size = 0.4, colour = "olivedrab3") + geom_line(data = chr6.pe.gc1, aes(x = start, y = mean), size = 0.3, alpha = 0.5, colour = "olivedrab3") + labs(x="Distance (Megabases)", y=expression(LD~(r^{2}))) + scale_x_continuous(breaks=c(0,2*10^6,4*10^6,6*10^6,8*10^6), labels=c("0","2","4","6","8")) + theme_bw()
ggsave("all.chr.pe.gc.pdf",p1,height=8,width=8,units="cm",dpi=250)
p1 <- ggplot() + geom_point(data = chr2.pe.gc1, aes(x = start, y = mean), size = 0.4, colour = "brown3") + geom_line(data = chr2.pe.gc1, aes(x = start, y = mean), size = 0.3, alpha = 0.5, colour = "brown3") + geom_point(data = chr3.pe.gc1, aes(x = start, y = mean), size = 0.4, colour = "magenta3") + geom_line(data = chr3.pe.gc1, aes(x = start, y = mean), size = 0.3, alpha = 0.5, colour = "magenta3") + geom_point(data = chr4.pe.gc1, aes(x = start, y = mean), size = 0.4, colour = "cyan3") + geom_line(data = chr4.pe.gc1, aes(x = start, y = mean), size = 0.3, alpha = 0.5, colour = "cyan3") + geom_point(data = chr5.pe.gc1, aes(x = start, y = mean), size = 0.4, colour = "gold3") + geom_line(data = chr5.pe.gc1, aes(x = start, y = mean), size = 0.3, alpha = 0.5, colour = "gold3") + geom_point(data = chr6.pe.gc1, aes(x = start, y = mean), size = 0.4, colour = "olivedrab3") + geom_line(data = chr6.pe.gc1, aes(x = start, y = mean), size = 0.3, alpha = 0.5, colour = "olivedrab3") + labs(x="Distance (Megabases)", y=expression(LD~(r^{2}))) + scale_x_continuous(breaks=c(0,2*10^6,4*10^6,6*10^6,8*10^6), labels=c("0","2","4","6","8")) + classic_theme()
p1 <- ggplot() + geom_point(data = chr2.pe.gc1, aes(x = start, y = mean), size = 0.4, colour = "brown3") + geom_line(data = chr2.pe.gc1, aes(x = start, y = mean), size = 0.3, alpha = 0.5, colour = "brown3") + geom_point(data = chr3.pe.gc1, aes(x = start, y = mean), size = 0.4, colour = "magenta3") + geom_line(data = chr3.pe.gc1, aes(x = start, y = mean), size = 0.3, alpha = 0.5, colour = "magenta3") + geom_point(data = chr4.pe.gc1, aes(x = start, y = mean), size = 0.4, colour = "cyan3") + geom_line(data = chr4.pe.gc1, aes(x = start, y = mean), size = 0.3, alpha = 0.5, colour = "cyan3") + geom_point(data = chr5.pe.gc1, aes(x = start, y = mean), size = 0.4, colour = "gold3") + geom_line(data = chr5.pe.gc1, aes(x = start, y = mean), size = 0.3, alpha = 0.5, colour = "gold3") + geom_point(data = chr6.pe.gc1, aes(x = start, y = mean), size = 0.4, colour = "olivedrab3") + geom_line(data = chr6.pe.gc1, aes(x = start, y = mean), size = 0.3, alpha = 0.5, colour = "olivedrab3") + labs(x="Distance (Megabases)", y=expression(LD~(r^{2}))) + scale_x_continuous(breaks=c(0,2*10^6,4*10^6,6*10^6,8*10^6), labels=c("0","2","4","6","8")) + theme_classic()
ggsave("all.chr.pe.gc.pdf",p1,height=8,width=8,units="cm",dpi=250)
ggplot() + geom_point(data = chr2.pe.it1, aes(x = start, y = mean), size = 0.4, colour = "brown3") + geom_line(data = chr2.pe.it1, aes(x = start, y = mean), size = 0.3, alpha = 0.5, colour = "brown3") + geom_point(data = chr3.pe.it1, aes(x = start, y = mean), size = 0.4, colour = "magenta3") + geom_line(data = chr3.pe.it1, aes(x = start, y = mean), size = 0.3, alpha = 0.5, colour = "magenta3") + geom_point(data = chr4.pe.it1, aes(x = start, y = mean), size = 0.4, colour = "cyan3") + geom_line(data = chr4.pe.it1, aes(x = start, y = mean), size = 0.3, alpha = 0.5, colour = "cyan3") + geom_point(data = chr5.pe.it1, aes(x = start, y = mean), size = 0.4, colour = "gold3") + geom_line(data = chr5.pe.it1, aes(x = start, y = mean), size = 0.3, alpha = 0.5, colour = "gold3") + geom_point(data = chr6.pe.it1, aes(x = start, y = mean), size = 0.4, colour = "olivedrab3") + geom_line(data = chr6.pe.it1, aes(x = start, y = mean), size = 0.3, alpha = 0.5, colour = "olivedrab3") + labs(x="Distance (Megabases)", y=expression(LD~(r^{2}))) + scale_x_continuous(breaks=c(0,2*10^6,4*10^6,6*10^6,8*10^6), labels=c("0","2","4","6","8")) + theme_classic()
p2 <- ggplot() + geom_point(data = chr2.pe.it1, aes(x = start, y = mean), size = 0.4, colour = "brown3") + geom_line(data = chr2.pe.it1, aes(x = start, y = mean), size = 0.3, alpha = 0.5, colour = "brown3") + geom_point(data = chr3.pe.it1, aes(x = start, y = mean), size = 0.4, colour = "magenta3") + geom_line(data = chr3.pe.it1, aes(x = start, y = mean), size = 0.3, alpha = 0.5, colour = "magenta3") + geom_point(data = chr4.pe.it1, aes(x = start, y = mean), size = 0.4, colour = "cyan3") + geom_line(data = chr4.pe.it1, aes(x = start, y = mean), size = 0.3, alpha = 0.5, colour = "cyan3") + geom_point(data = chr5.pe.it1, aes(x = start, y = mean), size = 0.4, colour = "gold3") + geom_line(data = chr5.pe.it1, aes(x = start, y = mean), size = 0.3, alpha = 0.5, colour = "gold3") + geom_point(data = chr6.pe.it1, aes(x = start, y = mean), size = 0.4, colour = "olivedrab3") + geom_line(data = chr6.pe.it1, aes(x = start, y = mean), size = 0.3, alpha = 0.5, colour = "olivedrab3") + labs(x="Distance (Megabases)", y=expression(LD~(r^{2}))) + scale_x_continuous(breaks=c(0,2*10^6,4*10^6,6*10^6,8*10^6), labels=c("0","2","4","6","8")) + theme_classic()
ggsave("all.chr.pe.it.pdf",p2,height=8,width=8,units="cm",dpi=250)
ggplot() + geom_point(data = chr2.tb.it1, aes(x = start, y = mean), size = 0.4, colour = "brown3") + geom_line(data = chr2.tb.it1, aes(x = start, y = mean), size = 0.3, alpha = 0.5, colour = "brown3") + geom_point(data = chr3.tb.it1, aes(x = start, y = mean), size = 0.4, colour = "magenta3") + geom_line(data = chr3.tb.it1, aes(x = start, y = mean), size = 0.3, alpha = 0.5, colour = "magenta3") + geom_point(data = chr4.tb.it1, aes(x = start, y = mean), size = 0.4, colour = "cyan3") + geom_line(data = chr4.tb.it1, aes(x = start, y = mean), size = 0.3, alpha = 0.5, colour = "cyan3") + geom_point(data = chr5.tb.it1, aes(x = start, y = mean), size = 0.4, colour = "gold3") + geom_line(data = chr5.tb.it1, aes(x = start, y = mean), size = 0.3, alpha = 0.5, colour = "gold3") + geom_point(data = chr6.tb.it1, aes(x = start, y = mean), size = 0.4, colour = "olivedrab3") + geom_line(data = chr6.tb.it1, aes(x = start, y = mean), size = 0.3, alpha = 0.5, colour = "olivedrab3") + labs(x="Distance (Megabases)", y=expression(LD~(r^{2}))) + scale_x_continuous(breaks=c(0,2*10^6,4*10^6,6*10^6,8*10^6), labels=c("0","2","4","6","8")) + theme_classic()
p3 <- ggplot() + geom_point(data = chr2.tb.it1, aes(x = start, y = mean), size = 0.4, colour = "brown3") + geom_line(data = chr2.tb.it1, aes(x = start, y = mean), size = 0.3, alpha = 0.5, colour = "brown3") + geom_point(data = chr3.tb.it1, aes(x = start, y = mean), size = 0.4, colour = "magenta3") + geom_line(data = chr3.tb.it1, aes(x = start, y = mean), size = 0.3, alpha = 0.5, colour = "magenta3") + geom_point(data = chr4.tb.it1, aes(x = start, y = mean), size = 0.4, colour = "cyan3") + geom_line(data = chr4.tb.it1, aes(x = start, y = mean), size = 0.3, alpha = 0.5, colour = "cyan3") + geom_point(data = chr5.tb.it1, aes(x = start, y = mean), size = 0.4, colour = "gold3") + geom_line(data = chr5.tb.it1, aes(x = start, y = mean), size = 0.3, alpha = 0.5, colour = "gold3") + geom_point(data = chr6.tb.it1, aes(x = start, y = mean), size = 0.4, colour = "olivedrab3") + geom_line(data = chr6.tb.it1, aes(x = start, y = mean), size = 0.3, alpha = 0.5, colour = "olivedrab3") + labs(x="Distance (Megabases)", y=expression(LD~(r^{2}))) + scale_x_continuous(breaks=c(0,2*10^6,4*10^6,6*10^6,8*10^6), labels=c("0","2","4","6","8")) + theme_classic()
ggsave("all.chr.tb.it.pdf",p2,height=8,width=8,units="cm",dpi=250)
ggplot() + geom_point(data = chr2.tb.gc1, aes(x = start, y = mean), size = 0.4, colour = "brown3") + geom_line(data = chr2.tb.gc1, aes(x = start, y = mean), size = 0.3, alpha = 0.5, colour = "brown3") + geom_point(data = chr3.tb.gc1, aes(x = start, y = mean), size = 0.4, colour = "magenta3") + geom_line(data = chr3.tb.gc1, aes(x = start, y = mean), size = 0.3, alpha = 0.5, colour = "magenta3") + geom_point(data = chr4.tb.gc1, aes(x = start, y = mean), size = 0.4, colour = "cyan3") + geom_line(data = chr4.tb.gc1, aes(x = start, y = mean), size = 0.3, alpha = 0.5, colour = "cyan3") + geom_point(data = chr5.tb.gc1, aes(x = start, y = mean), size = 0.4, colour = "gold3") + geom_line(data = chr5.tb.gc1, aes(x = start, y = mean), size = 0.3, alpha = 0.5, colour = "gold3") + geom_point(data = chr6.tb.gc1, aes(x = start, y = mean), size = 0.4, colour = "olivedrab3") + geom_line(data = chr6.tb.gc1, aes(x = start, y = mean), size = 0.3, alpha = 0.5, colour = "olivedrab3") + labs(x="Distance (Megabases)", y=expression(LD~(r^{2}))) + scale_x_continuous(breaks=c(0,2*10^6,4*10^6,6*10^6,8*10^6), labels=c("0","2","4","6","8")) + theme_classic()
p4 <- ggplot() + geom_point(data = chr2.tb.gc1, aes(x = start, y = mean), size = 0.4, colour = "brown3") + geom_line(data = chr2.tb.gc1, aes(x = start, y = mean), size = 0.3, alpha = 0.5, colour = "brown3") + geom_point(data = chr3.tb.gc1, aes(x = start, y = mean), size = 0.4, colour = "magenta3") + geom_line(data = chr3.tb.gc1, aes(x = start, y = mean), size = 0.3, alpha = 0.5, colour = "magenta3") + geom_point(data = chr4.tb.gc1, aes(x = start, y = mean), size = 0.4, colour = "cyan3") + geom_line(data = chr4.tb.gc1, aes(x = start, y = mean), size = 0.3, alpha = 0.5, colour = "cyan3") + geom_point(data = chr5.tb.gc1, aes(x = start, y = mean), size = 0.4, colour = "gold3") + geom_line(data = chr5.tb.gc1, aes(x = start, y = mean), size = 0.3, alpha = 0.5, colour = "gold3") + geom_point(data = chr6.tb.gc1, aes(x = start, y = mean), size = 0.4, colour = "olivedrab3") + geom_line(data = chr6.tb.gc1, aes(x = start, y = mean), size = 0.3, alpha = 0.5, colour = "olivedrab3") + labs(x="Distance (Megabases)", y=expression(LD~(r^{2}))) + scale_x_continuous(breaks=c(0,2*10^6,4*10^6,6*10^6,8*10^6), labels=c("0","2","4","6","8")) + theme_classic()
p4
ggsave("all.chr.tb.it.pdf",p3,height=8,width=8,units="cm",dpi=250)
ggsave("all.chr.tb.gc.pdf",p4,height=8,width=8,units="cm",dpi=250)
head(chr2.tb.gc1)
pe.gc <- data.frame(chr2=chr2.pe.gc1$mean, chr3=chr3.pe.gc1$mean, chr4=chr4.pe.gc1$mean, chr5=chr5.pe.gc1$mean, chr6=chr6.pe.gc1$mean)
head(pe.gc)
nrow(pe.gc)
mean(chr2.pe.gc1$mean)
0.09719645 * 80
0.09719645 * 100
head(chr2.pe.gc)
tail(chr2.pe.gc)
mean(chr2.pe.gc$rsq)
head(pe.gc)
library(reshape2)
pegcm <- melt(pe.gc)
head(pegcm)
ggplot(pegcm, aes(x=variable, y=value)) + geom_boxplot() + geom_jitter(shape=16, position=position_jitter(0.2)) + scale_color_manual(values=c("brown3", "magenta3", "cyan3", "gold3", "olivedrab3"))
ggplot(pegcm, aes(x=variable, y=value, color=variable)) + geom_boxplot() + geom_jitter(shape=16, position=position_jitter(0.2)) + scale_color_manual(values=c("brown3", "magenta3", "cyan3", "gold3", "olivedrab3"))
ggplot(pegcm, aes(x=variable, y=value, color=variable)) + geom_boxplot() + geom_jitter(shape=16, position=position_jitter(0.2)) + scale_color_manual(values=c("brown3", "magenta3", "cyan3", "gold3", "olivedrab3")) + theme_classic()
colnames(pegcm) <- c("Chromosomes", "r2")
ggplot(pegcm, aes(x=Chromosomes, y=r2, color=Chromosomes)) + geom_boxplot() + geom_jitter(shape=16, position=position_jitter(0.2)) + scale_color_manual(values=c("brown3", "magenta3", "cyan3", "gold3", "olivedrab3")) + theme_classic()
pe.it <- data.frame(chr2=chr2.pe.it1$mean, chr3=chr3.pe.it1$mean, chr4=chr4.pe.it1$mean, chr5=chr5.pe.it1$mean, chr6=chr6.pe.it1$mean)
peitm <- melt(pe.it)
colnames(peitm) <- c("Chromosomes", "r2")
p6 <- ggplot(peitm, aes(x=Chromosomes, y=r2, color=Chromosomes)) + geom_boxplot() + geom_jitter(shape=16, position=position_jitter(0.2)) + scale_color_manual(values=c("brown3", "magenta3", "cyan3", "gold3", "olivedrab3")) + theme_classic()
ggsave("mean.all.chr.tb.it.pdf",p6,height=8,width=8,units="cm",dpi=250)
p5 <- ggplot(pegcm, aes(x=Chromosomes, y=r2, color=Chromosomes)) + geom_boxplot() + geom_jitter(shape=16, position=position_jitter(0.2)) + scale_color_manual(values=c("brown3", "magenta3", "cyan3", "gold3", "olivedrab3")) + theme_classic()
ggsave("mean.all.chr.pe.it.pdf",p6,height=8,width=8,units="cm",dpi=250)
ggsave("mean.all.chr.pe.gc.pdf",p5,height=8,width=8,units="cm",dpi=250)
tb.it <- data.frame(chr2=chr2.tb.it1$mean, chr3=chr3.tb.it1$mean, chr4=chr4.tb.it1$mean, chr5=chr5.tb.it1$mean, chr6=chr6.tb.it1$mean)
tbitm <- melt(tb.it)
colnames(tbitm) <- c("Chromosomes", "r2")
p7 <- ggplot(tbitm, aes(x=Chromosomes, y=r2, color=Chromosomes)) + geom_boxplot() + geom_jitter(shape=16, position=position_jitter(0.2)) + scale_color_manual(values=c("brown3", "magenta3", "cyan3", "gold3", "olivedrab3")) + theme_classic()
ggsave("mean.all.chr.tb.it.pdf",p7,height=8,width=8,units="cm",dpi=250)
tb.gc <- data.frame(chr2=chr2.tb.gc1$mean, chr3=chr3.tb.gc1$mean, chr4=chr4.tb.gc1$mean, chr5=chr5.tb.gc1$mean, chr6=chr6.tb.gc1$mean)
tbgcm <- melt(tb.gc)
colnames(tbgcm) <- c("Chromosomes", "r2")
p8 <- ggplot(tbgcm, aes(x=Chromosomes, y=r2, color=Chromosomes)) + geom_boxplot() + geom_jitter(shape=16, position=position_jitter(0.2)) + scale_color_manual(values=c("brown3", "magenta3", "cyan3", "gold3", "olivedrab3")) + theme_classic()
ggsave("mean.all.chr.tb.gc.pdf",p8,height=8,width=8,units="cm",dpi=250)
ggsave("all.chr.pe.gc.pdf",p1,height=8,width=12,units="cm",dpi=250)
ggsave("all.chr.pe.gc.pdf",p1,height=8,width=15,units="cm",dpi=250)
ggsave("all.chr.pe.it.pdf",p2,height=8,width=15,units="cm",dpi=250)
ggsave("all.chr.tb.it.pdf",p3,height=8,width=15,units="cm",dpi=250)
ggsave("all.chr.tb.gc.pdf",p4,height=8,width=15,units="cm",dpi=250)
ggsave("mean.all.chr.tb.gc.pdf",p8,height=8,width=15,units="cm",dpi=250)
ggsave("mean.all.chr.tb.it.pdf",p7,height=8,width=15,units="cm",dpi=250)
ggsave("mean.all.chr.pe.gc.pdf",p5,height=8,width=15,units="cm",dpi=250)
ggsave("mean.all.chr.pe.it.pdf",p6,height=8,width=15,units="cm",dpi=250)
quit()
ls()
dir()
dfr <- read.delim("snp-thin.blocks.det",sep="",header=T,check.names=F,stringsAsFactors=F)
chr3.pe.gc.bk <- read.delim("country_correct/peach.gc-thin.blocks.det",sep="",header=T,check.names=F,stringsAsFactors=F)
dir("country_correct/")
chr3.pe.gc.bk <- read.delim("country_correct/peach.greece.thin2.blocks.det",sep="",header=T,check.names=F,stringsAsFactors=F)
chr3.pe.it.bk <- read.delim("country_correct/peach.italy.thin2.blocks.det",sep="",header=T,check.names=F,stringsAsFactors=F)
chr3.tb.all.bk <- read.delim("country_correct/tobacco.all.thin2.blocks.det",sep="",header=T,check.names=F,stringsAsFactors=F)
chr2.pe.gc.bk <- read.delim("LD_decay_chr2/peach.gc-thin2.blocks.det",sep="",header=T,check.names=F,stringsAsFactors=F)
chr2.pe.it.bk <- read.delim("LD_decay_chr2/peach.it-thin2.blocks.det",sep="",header=T,check.names=F,stringsAsFactors=F)
chr2.tb.all.bk <- read.delim("LD_decay_chr2/tobacco.all-thin2.blocks.det",sep="",header=T,check.names=F,stringsAsFactors=F)
chr2.tb.all.bk <- read.delim("LD_decay_chr2/tobacco-thin2.blocks.det",sep="",header=T,check.names=F,stringsAsFactors=F)
chr4.pe.gc.bk <- read.delim("LD_decay_chr4/peach.gc-thin2.blocks.det",sep="",header=T,check.names=F,stringsAsFactors=F)
chr4.pe.it.bk <- read.delim("LD_decay_chr4/peach.it-thin2.blocks.det",sep="",header=T,check.names=F,stringsAsFactors=F)
chr4.tb.all.bk <- read.delim("LD_decay_chr4/tobacco-thin2.blocks.det",sep="",header=T,check.names=F,stringsAsFactors=F)
chr5.pe.gc.bk <- read.delim("LD_decay_chr5/peach.gc-thin2.blocks.det",sep="",header=T,check.names=F,stringsAsFactors=F)
chr5.pe.it.bk <- read.delim("LD_decay_chr5/peach.it-thin2.blocks.det",sep="",header=T,check.names=F,stringsAsFactors=F)
chr5.tb.all.bk <- read.delim("LD_decay_chr5/tobacco-thin2.blocks.det",sep="",header=T,check.names=F,stringsAsFactors=F)
chr6.pe.gc.bk <- read.delim("LD_decay_chr6/peach.gc-thin2.blocks.det",sep="",header=T,check.names=F,stringsAsFactors=F)
chr6.pe.it.bk <- read.delim("LD_decay_chr6/peach.it-thin2.blocks.det",sep="",header=T,check.names=F,stringsAsFactors=F)
chr6.tb.all.bk <- read.delim("LD_decay_chr6/tobacco-thin2.blocks.det",sep="",header=T,check.names=F,stringsAsFactors=F)
colnames(chr2.pe.gc.bk) <- tolower(colnames(chr2.pe.gc.bk))
colnames(chr2.pe.it.bk) <- tolower(colnames(chr2.pe.it.bk))
colnames(chr2.tb.all.bk) <- tolower(colnames(chr2.tb.all.bk))
colnames(chr3.pe.gc.bk) <- tolower(colnames(chr3.pe.gc.bk))
colnames(chr3.pe.it.bk) <- tolower(colnames(chr3.pe.it.bk))
colnames(chr3.tb.all.bk) <- tolower(colnames(chr3.tb.all.bk))
colnames(chr4.pe.gc.bk) <- tolower(colnames(chr4.pe.gc.bk))
colnames(chr4.pe.it.bk) <- tolower(colnames(chr4.pe.it.bk))
colnames(chr4.tb.all.bk) <- tolower(colnames(chr4.tb.all.bk))
colnames(chr5.pe.gc.bk) <- tolower(colnames(chr5.pe.gc.bk))
colnames(chr5.pe.it.bk) <- tolower(colnames(chr5.pe.it.bk))
colnames(chr5.tb.all.bk) <- tolower(colnames(chr5.tb.all.bk))
colnames(chr6.pe.gc.bk) <- tolower(colnames(chr6.pe.gc.bk))
colnames(chr6.pe.it.bk) <- tolower(colnames(chr6.pe.it.bk))
colnames(chr6.tb.all.bk) <- tolower(colnames(chr6.tb.all.bk))
ggplot() + geom_density(data=chr2.pe.gc.bk, aes(x=kb), size=0.5,colour="brown3") + labs(x="LD block length (Kb)",y="Density") + theme_classic()
library(ggplot2)
ggplot() + geom_density(data=chr2.pe.gc.bk, aes(x=kb), size=0.5,colour="brown3") + labs(x="LD block length (Kb)",y="Density") + theme_classic()
ggplot() + geom_density(data=chr2.pe.gc.bk, aes(x=kb), size=0.5,colour="brown3") + geom_density(data=chr3.pe.gc.bk, aes(x=kb), size=0.5,colour="brown3") + geom_density(data=chr4.pe.gc.bk, aes(x=kb), size=0.5,colour="brown3") + geom_density(data=chr5.pe.gc.bk, aes(x=kb), size=0.5,colour="brown3") + geom_density(data=chr6.pe.gc.bk, aes(x=kb), size=0.5,colour="brown3") + labs(x="LD block length (Kb)",y="Density") + theme_classic()
ggplot() + geom_density(data=chr2.pe.gc.bk, aes(x=kb), size=0.5,colour="brown3") + geom_density(data=chr3.pe.gc.bk, aes(x=kb), size=0.5,colour="magenta3") + geom_density(data=chr4.pe.gc.bk, aes(x=kb), size=0.5,colour="cyan3") + geom_density(data=chr5.pe.gc.bk, aes(x=kb), size=0.5,colour="gold3") + geom_density(data=chr6.pe.gc.bk, aes(x=kb), size=0.5,colour="olivedrab3") + labs(x="LD block length (Kb)",y="Density") + theme_classic()
b1 <- ggplot() + geom_density(data=chr2.pe.gc.bk, aes(x=kb), size=0.5,colour="brown3") + geom_density(data=chr3.pe.gc.bk, aes(x=kb), size=0.5,colour="magenta3") + geom_density(data=chr4.pe.gc.bk, aes(x=kb), size=0.5,colour="cyan3") + geom_density(data=chr5.pe.gc.bk, aes(x=kb), size=0.5,colour="gold3") + geom_density(data=chr6.pe.gc.bk, aes(x=kb), size=0.5,colour="olivedrab3") + labs(x="LD block length (Kb)",y="Density") + theme_classic()
ggplot() + geom_density(data=chr2.pe.it.bk, aes(x=kb), size=0.5,colour="brown3") + geom_density(data=chr3.pe.it.bk, aes(x=kb), size=0.5,colour="magenta3") + geom_density(data=chr4.pe.it.bk, aes(x=kb), size=0.5,colour="cyan3") + geom_density(data=chr5.pe.it.bk, aes(x=kb), size=0.5,colour="gold3") + geom_density(data=chr6.pe.it.bk, aes(x=kb), size=0.5,colour="olivedrab3") + labs(x="LD block length (Kb)",y="Density") + theme_classic()
b2 <- ggplot() + geom_density(data=chr2.pe.it.bk, aes(x=kb), size=0.5,colour="brown3") + geom_density(data=chr3.pe.it.bk, aes(x=kb), size=0.5,colour="magenta3") + geom_density(data=chr4.pe.it.bk, aes(x=kb), size=0.5,colour="cyan3") + geom_density(data=chr5.pe.it.bk, aes(x=kb), size=0.5,colour="gold3") + geom_density(data=chr6.pe.it.bk, aes(x=kb), size=0.5,colour="olivedrab3") + labs(x="LD block length (Kb)",y="Density") + theme_classic()
ggplot() + geom_density(data=chr2.tb.all.bk, aes(x=kb), size=0.5,colour="brown3") + geom_density(data=chr3.tb.all.bk, aes(x=kb), size=0.5,colour="magenta3") + geom_density(data=chr4.tb.all.bk, aes(x=kb), size=0.5,colour="cyan3") + geom_density(data=chr5.tb.all.bk, aes(x=kb), size=0.5,colour="gold3") + geom_density(data=chr6.tb.all.bk, aes(x=kb), size=0.5,colour="olivedrab3") + labs(x="LD block length (Kb)",y="Density") + theme_classic()
b3 <- ggplot() + geom_density(data=chr2.tb.all.bk, aes(x=kb), size=0.5,colour="brown3") + geom_density(data=chr3.tb.all.bk, aes(x=kb), size=0.5,colour="magenta3") + geom_density(data=chr4.tb.all.bk, aes(x=kb), size=0.5,colour="cyan3") + geom_density(data=chr5.tb.all.bk, aes(x=kb), size=0.5,colour="gold3") + geom_density(data=chr6.tb.all.bk, aes(x=kb), size=0.5,colour="olivedrab3") + labs(x="LD block length (Kb)",y="Density") + theme_classic()
ggsave("pe.gc.block.pdf",b1,height=8,width=15,units="cm",dpi=250)
ggsave("pe.it.block.pdf",b2,height=8,width=15,units="cm",dpi=250)
ggsave("tb.all.block.pdf",b3,height=8,width=15,units="cm",dpi=250)
quit()
ls()
head(chr2.pe.gc1)
mean(chr2.pe.gc1)
mean(chr2.pe.gc1$mean)
mean(chr2.pe.it1$mean)
mean(chr2.tb.it1$mean)
mean(chr2.tb.gc1$mean)
mean(chr3.pe.gc1$mean)
mean(chr3.pe.it1$mean)
mean(chr3.tb.it1$mean)
mean(chr3.tb.gc1$mean)
mean(chr4.pe.gc1$mean)
mean(chr4.pe.it1$mean)
mean(chr4.tb.it1$mean)
mean(chr4.tb.gc1$mean)
mean(chr5.pe.gc1$mean)
mean(chr5.pe.it1$mean)
mean(chr5.tb.it1$mean)
mean(chr5.tb.gc1$mean)
mean(chr6.pe.gc1$mean)
mean(chr6.pe.it1$mean)
mean(chr6.tb.it1$mean)
mean(chr6.tb.gc1$mean)
ls()
head(chr2.pe.gc.bk)
mean(chr2.pe.gc.bk$kb)
mean(chr2.pe.it.bk$kb)
mean(chr2.tb.all.bk$kb)
mean(chr3.pe.gc.bk$kb)
mean(chr3.pe.it.bk$kb)
mean(chr3.tb.all.bk$kb)
mean(chr4.tb.all.bk$kb)
mean(chr5.tb.all.bk$kb)
mean(chr6.tb.all.bk$kb)
mean(chr4.pe.gc.bk$kb)
mean(chr5.pe.gc.bk$kb)
mean(chr6.pe.gc.bk$kb)
mean(chr4.pe.it.bk$kb)
mean(chr5.pe.it.bk$kb)
mean(chr6.pe.it.bk$kb)
head(chr2.pe.it.bk)
chr2.pe.it.bk[order(kb, nsnps)]
chr2.pe.it.bk[order(kb),]
chr2.pe.it.bk[order(chr2.pe.it.bk$kb),]
head(chr2.pe.it.bk[order(chr2.pe.it.bk$kb),])
tail(chr2.pe.it.bk[order(chr2.pe.it.bk$kb),])
head(chr2.pe.gc.bk[order(chr2.pe.gc.bk$kb),])
tail(chr2.pe.gc.bk[order(chr2.pe.gc.bk$kb),])
head(chr2.tb.all.bk[order(chr2.tb.all.bk$kb),])
tail(chr2.tb.all.bk[order(chr2.tb.all.bk$kb),])
tail(chr3.pe.gc.bk[order(chr3.pe.gc.bk$kb),])
head(chr3.pe.gc.bk[order(chr3.pe.gc.bk$kb),])
tail(chr3.pe.gc.bk[order(chr3.pe.gc.bk$kb),])
head(chr3.pe.it.bk[order(chr3.pe.it.bk$kb),])
tail(chr3.pe.it.bk[order(chr3.pe.it.bk$kb),])
head(chr3.tb.all.bk[order(chr3.tb.all.bk$kb),])
tail(chr3.tb.all.bk[order(chr3.tb.all.bk$kb),])
head(chr4.pe.gc.bk[order(chr4.pe.gc.bk$kb),])
tail(chr4.pe.gc.bk[order(chr4.pe.gc.bk$kb),])
head(chr4.pe.it.bk[order(chr4.pe.it.bk$kb),])
tail(chr4.pe.it.bk[order(chr4.pe.it.bk$kb),])
head(chr4.tb.all.bk[order(chr4.tb.all.bk$kb),])
tail(chr4.tb.all.bk[order(chr4.tb.all.bk$kb),])
head(chr5.pe.gc.bk[order(chr5.pe.gc.bk$kb),])
tail(chr5.pe.gc.bk[order(chr5.pe.gc.bk$kb),])
head(chr5.pe.it.bk[order(chr5.pe.it.bk$kb),])
tail(chr5.pe.it.bk[order(chr5.pe.it.bk$kb),])
head(chr5.tb.all.bk[order(chr5.tb.all.bk$kb),])
tail(chr5.tb.all.bk[order(chr5.tb.all.bk$kb),])
head(chr6.pe.gc.bk[order(chr6.pe.gc.bk$kb),])
tail(chr6.pe.gc.bk[order(chr6.pe.gc.bk$kb),])
head(chr6.pe.it.bk[order(chr6.pe.it.bk$kb),])
tail(chr6.pe.it.bk[order(chr6.pe.it.bk$kb),])
head(chr6.tb.all.bk[order(chr6.tb.all.bk$kb),])
tail(chr6.tb.all.bk[order(chr6.tb.all.bk$kb),])
ls()
len(chr2.pe.gc.bk$kb)
length(chr2.pe.gc.bk$kb)
nrow(chr2.pe.gc.bk$kb)
nrow(chr2.pe.gc.bk)
length(chr2.pe.it.bk$kb)
nrow(chr3.pe.gc.bk)
length(chr3.pe.it.bk$kb)
length(chr3.pe.gc.bk$kb)
length(chr4.pe.it.bk$kb)
length(chr4.pe.gc.bk$kb)
length(chr5.pe.it.bk$kb)
length(chr5.pe.gc.bk$kb)
length(chr6.pe.it.bk$kb)
length(chr6.pe.gc.bk$kb)
length(chr2.tb.all.bk$kb)
length(chr3.tb.all.bk$kb)
length(chr4.tb.all.bk$kb)
length(chr5.tb.all.bk$kb)
length(chr6.tb.all.bk$kb)
quit()
