norm <- function(x) x/sum(x)
dir()
pe.gc <- (scan("pe.gc_folded_chr3.sfs"))
pvar<- (1-pe.gc[1]-pe.gc[length(sfs)])*100
pvar<- (1-pe.gc[1]-pe.gc[length(pe.gc)])*100
pvar
pe.gc<-norm(pe.gc[-c(1,length(pe.gc))])
pe.gc
p1 <- barplot(pe.gc,xlab="Chromosomes",names=1:length(pe.gc),ylab="Proportions",main="Chromosome 3 SFS using Peach individuals from Greece",col='green4')
p1 <- barplot(pe.gc,xlab="Chromosomes",names=1:length(pe.gc),ylab="Proportions",main="Chromosome 3 SFS using clones from Peach and Greece",col='green4')
p1 <- barplot(pe.gc,xlab="Chromosomes",names=1:length(pe.gc),ylab="Proportions",main="Chromosome 3 SFS using clones (2n + 1) from Peach and Greece",col='green4')
ggsave("snp-thin-ld-blocks.png",p,height=8,width=8,units="cm",dpi=250)
p1 <- barplot(pe.gc,xlab="Chromosomes",names=1:length(pe.gc),ylab="Proportions",main="Chromosome 3 SFS using clones (2n + 1) from Peach and Greece",col='green4')
pdf("pe.gc.sfs.pdf")
p1 <- barplot(pe.gc,xlab="Chromosomes",names=1:length(pe.gc),ylab="Proportions",main="Chromosome 3 SFS using clones (2n + 1) from Peach and Greece",col='green4')
dev.off()
dir()
pe.it <- (scan("pe.it_folded_chr3.sfs"))
pe.it<-norm(pe.it[-c(1,length(pe.it))])
p2 <- barplot(pe.it,xlab="Chromosomes",names=1:length(pe.it),ylab="Proportions",main="Chromosome 3 SFS using 12 clones (2n + 1) from Peach and Italy",col='green4')
p1 <- barplot(pe.gc,xlab="Chromosomes",names=1:length(pe.gc),ylab="Proportions",main="Chromosome 3 SFS using 14 clones (2n + 1) from Peach and Greece",col='green4')
pdf(pe.gc.sfs.pdf)
pdf("pe.gc.sfs.pdf")
p1 <- barplot(pe.gc,xlab="Chromosomes",names=1:length(pe.gc),ylab="Proportions",main="Chromosome 3 SFS using 14 clones (2n + 1) from Peach and Greece",col='green4')
dev.off()
pdf("pe.it.sfs.pdf")
p2 <- barplot(pe.it,xlab="Chromosomes",names=1:length(pe.it),ylab="Proportions",main="Chromosome 3 SFS using 12 clones (2n + 1) from Peach and Italy",col='green4')
dev.off()
dir()
tb.gc <- (scan("tb.gc_folded_chr3.sfs"))
tb.gc<-norm(tb.gc[-c(1,length(tb.gc))])
pdf("tb.gc.sfs.pdf")
p3 <- barplot(tb.gc,xlab="Chromosomes",names=1:length(tb.gc),ylab="Proportions",main="Chromosome 3 SFS using 9 clones (2n + 1) from Tobacco and Greece",col='green4')
dev.off()
pdf("tb.gc.sfs.pdf")
p3 <- barplot(tb.gc,xlab="Chromosomes",names=1:length(tb.gc),ylab="Proportions",main="Chromosome 3 SFS using 9 clones (2n + 1) from Tobacco and Greece",col='red3')
dev.off()
pdf("tb.it.sfs.pdf")
tb.it <- (scan("tb.it_folded_chr3.sfs"))
tb.it<-norm(tb.it[-c(1,length(tb.it))])
p3 <- barplot(tb.it,xlab="Chromosomes",names=1:length(tb.it),ylab="Proportions",main="Chromosome 3 SFS using 6 clones (2n + 1) from Tobacco and Italy",col='red3')
dev.off()
quit()
dir()
chr2.pe.gc <- (scan("pe.gc_folded_chr2.sfs"))
chr2.pe.it <- (scan("pe.it_folded_chr2.sfs"))
chr2.tb.gc <- (scan("tb.gc_folded_chr2.sfs"))
chr2.tb.it <- (scan("tb.it_folded_chr2.sfs"))
chr3.pe.gc <- (scan("pe.gc_folded_chr3.sfs"))
chr3.pe.it <- (scan("pe.it_folded_chr3.sfs"))
chr3.tb.it <- (scan("tb.it_folded_chr3.sfs"))
chr3.tb.gc <- (scan("tb.gc_folded_chr3.sfs"))
chr4.pe.gc <- (scan("pe.gc_folded_chr4.sfs"))
chr4.pe.it <- (scan("pe.it_folded_chr4.sfs"))
chr4.tb.it <- (scan("tb.it_folded_chr4.sfs"))
chr4.tb.gc <- (scan("tb.gc_folded_chr4.sfs"))
chr5.pe.gc <- (scan("pe.gc_folded_chr5.sfs"))
chr5.pe.it <- (scan("pe.it_folded_chr5.sfs"))
chr5.tb.it <- (scan("tb.it_folded_chr5.sfs"))
chr5.tb.gc <- (scan("tb.gc_folded_chr5.sfs"))
chr6.pe.gc <- (scan("pe.gc_folded_chr6.sfs"))
chr6.pe.it <- (scan("pe.it_folded_chr6.sfs"))
chr6.tb.it <- (scan("tb.it_folded_chr6.sfs"))
chr6.tb.gc <- (scan("tb.gc_folded_chr6.sfs"))
chr2.pe.gc<-norm(chr2.pe.gc[-c(1,length(chr2.pe.gc))])
chr2.pe.it<-norm(chr2.pe.it[-c(1,length(chr2.pe.it))])
chr2.tb.it<-norm(chr2.tb.it[-c(1,length(chr2.tb.it))])
chr2.tb.gc<-norm(chr2.tb.gc[-c(1,length(chr2.tb.gc))])
chr3.pe.gc<-norm(chr3.pe.gc[-c(1,length(chr3.pe.gc))])
chr3.pe.it<-norm(chr3.pe.it[-c(1,length(chr3.pe.it))])
chr3.tb.it<-norm(chr3.tb.it[-c(1,length(chr3.tb.it))])
chr3.tb.gc<-norm(chr3.tb.gc[-c(1,length(chr3.tb.gc))])
chr4.pe.gc<-norm(chr4.pe.gc[-c(1,length(chr4.pe.gc))])
chr4.pe.it<-norm(chr4.pe.it[-c(1,length(chr4.pe.it))])
chr4.tb.it<-norm(chr4.tb.it[-c(1,length(chr4.tb.it))])
chr4.tb.gc<-norm(chr4.tb.gc[-c(1,length(chr4.tb.gc))])
chr5.pe.gc<-norm(chr5.pe.gc[-c(1,length(chr5.pe.gc))])
chr5.pe.it<-norm(chr5.pe.it[-c(1,length(chr5.pe.it))])
chr5.tb.it<-norm(chr5.tb.it[-c(1,length(chr5.tb.it))])
chr5.tb.gc<-norm(chr5.tb.gc[-c(1,length(chr5.tb.gc))])
chr6.pe.gc<-norm(chr6.pe.gc[-c(1,length(chr6.pe.gc))])
chr6.pe.it<-norm(chr6.pe.it[-c(1,length(chr6.pe.it))])
chr6.tb.it<-norm(chr6.tb.it[-c(1,length(chr6.tb.it))])
chr6.tb.gc<-norm(chr6.tb.gc[-c(1,length(chr6.tb.gc))])
chr2.pe.gc
chr3.pe.gc
pe.gc <- data.frame(Chr2=chr2.pe.gc, Chr3=chr3.pe.gc, Chr4=chr4.pe.gc, Chr5=chr5.pe.gc, Chr6=chr6.pe.gc)
pe.gc
library(reshape2)
pegcm = melt(pe.gc)
pegcm
head(pegcm)
colnames(pegcm) <- c("Chromosome", "Proportions")
head(pegcm)
ggplot(data=pegcm, aes(x=Chromosome, y=Proportions, fill=Chromosome)) + geom_bar(stat="identity", position=position_dodge()) + scale_color_manual(values=c("brown3", "magenta3", "cyan3", "gold3", "olivedrab3")) + theme_classic()
library(ggplot2)
ggplot(data=pegcm, aes(x=, y=Proportions, fill=Chromosome)) + geom_bar(stat="identity", position=position_dodge()) + scale_color_manual(values=c("brown3", "magenta3", "cyan3", "gold3", "olivedrab3")) + theme_classic()
pegcm
pe.gc
pe.gc$chr <- c(1:27)
pe.gc
pegcm = melt(pe.gc)
pegcm
pegcm = melt(pe.gc, id=pe.gc$chr)
library(dplyr)
pe.gc %>% gather(key, value, -chr) %>% ggplot(aes(x=chr, y=value, fill = key)) + geom_col(position = "dodge")
library(tidyr)
library(tidyverse)
install.packages("tidyverse")
library(tidyverse)
pe.gc %>% gather(key, value, -chr) %>% ggplot(aes(x=chr, y=value, fill = key)) + geom_col(position = "dodge")
pe.gc %>% gather(key, value, -chr) %>% ggplot(aes(x=chr, y=value, fill = key)) + geom_col(position = "dodge") + + scale_color_manual(values=c("brown3", "magenta3", "cyan3", "gold3", "olivedrab3")) + theme_classic()
pe.gc %>% gather(key, value, -chr) %>% ggplot(aes(x=chr, y=value, fill = key)) + geom_col(position = "dodge") + scale_color_manual(values=c("brown3", "magenta3", "cyan3", "gold3", "olivedrab3")) + theme_classic()
pe.gc %>% gather(key, value, -chr)
pegcm <- pe.gc %>% gather(key, value, -chr)
colnames(pegcm) <- c("Individuals","Chromosome", "Proportions")
ggplot(pegcm, aes(x=Individuals, y=Proportions, fill = Chromosome)) + geom_col(position = "dodge") + scale_color_manual(values=c("brown3", "magenta3", "cyan3", "gold3", "olivedrab3")) + theme_classic()
ggplot(pegcm, aes(x=Individuals, y=Proportions, fill = Chromosome)) + geom_bar(position = "dodge") + scale_color_manual(values=c("brown3", "magenta3", "cyan3", "gold3", "olivedrab3")) + theme_classic()
ggplot(pegcm, aes(x=Individuals, y=Proportions, fill = Chromosome)) + geom_bar(stat="identity") + scale_color_manual(values=c("brown3", "magenta3", "cyan3", "gold3", "olivedrab3")) + theme_classic()
ggplot(pegcm, aes(x=Individuals, y=Proportions, fill = Chromosome)) + geom_bar(stat="identity", position=position_dodge()) + scale_color_manual(values=c("brown3", "magenta3", "cyan3", "gold3", "olivedrab3")) + theme_classic()
ggplot(pegcm, aes(x=Individuals, y=Proportions, color = Chromosome)) + geom_bar(stat="identity", position=position_dodge()) + scale_color_manual(values=c("brown3", "magenta3", "cyan3", "gold3", "olivedrab3")) + theme_classic()
ggplot(pegcm, aes(x=Individuals, y=Proportions, color = Chromosome)) + geom_bar(position=position_dodge()) + scale_color_manual(values=c("brown3", "magenta3", "cyan3", "gold3", "olivedrab3")) + theme_classic()
ggplot() + geom_bar(pegcm, aes(x=Individuals, y=Proportions, color=Chromosome), position=position_dodge()) + scale_color_manual(values=c("brown3", "magenta3", "cyan3", "gold3", "olivedrab3")) + theme_classic()
ggplot(pegcm, aes(x=Individuals, y=Proportions, color = Chromosome)) + geom_bar(stat="identity", position=position_dodge()) + scale_color_manual(values=c("brown3", "magenta3", "cyan3", "gold3", "olivedrab3")) + theme_classic()
ggplot(pegcm, aes(x=Individuals, y=Proportions, fill = Chromosome)) + geom_bar(stat="identity", position=position_dodge()) + scale_fill_manual(values=c("brown3", "magenta3", "cyan3", "gold3", "olivedrab3")) + theme_classic()
s1 <- ggplot(pegcm, aes(x=Individuals, y=Proportions, fill = Chromosome)) + geom_bar(stat="identity", position=position_dodge()) + scale_fill_manual(values=c("brown3", "magenta3", "cyan3", "gold3", "olivedrab3")) + theme_classic()
pe.it <- data.frame(Chr2=chr2.pe.it, Chr3=chr3.pe.it, Chr4=chr4.pe.it, Chr5=chr5.pe.it, Chr6=chr6.pe.it)
head(pe.it)
nrow(pe.it)
pe.it$chr <- c(1:nrow(pe.it))
pe.it
peitm <- pe.it %>% gather(key, value, -chr)
peitm
colnames(peitm) <- c("Individuals","Chromosome", "Proportions")
s2 <- ggplot(peitm, aes(x=Individuals, y=Proportions, fill = Chromosome)) + geom_bar(stat="identity", position=position_dodge()) + scale_fill_manual(values=c("brown3", "magenta3", "cyan3", "gold3", "olivedrab3")) + theme_classic()
ggplot(peitm, aes(x=Individuals, y=Proportions, fill = Chromosome)) + geom_bar(stat="identity", position=position_dodge()) + scale_fill_manual(values=c("brown3", "magenta3", "cyan3", "gold3", "olivedrab3")) + theme_classic()
tb.gc <- data.frame(Chr2=chr2.tb.gc, Chr3=chr3.tb.gc, Chr4=chr4.tb.gc, Chr5=chr5.tb.gc, Chr6=chr6.tb.gc)
tb.gc$chr <- c(1:nrow(tb.gc))
tbgcm <- tb.gc %>% gather(key, value, -chr)
colnames(tbgcm) <- c("Individuals","Chromosome", "Proportions")
s3 <- ggplot(tbgcm, aes(x=Individuals, y=Proportions, fill = Chromosome)) + geom_bar(stat="identity", position=position_dodge()) + scale_fill_manual(values=c("brown3", "magenta3", "cyan3", "gold3", "olivedrab3")) + theme_classic()
ggplot(tbgcm, aes(x=Individuals, y=Proportions, fill = Chromosome)) + geom_bar(stat="identity", position=position_dodge()) + scale_fill_manual(values=c("brown3", "magenta3", "cyan3", "gold3", "olivedrab3")) + theme_classic()
tb.it <- data.frame(Chr2=chr2.tb.it, Chr3=chr3.tb.it, Chr4=chr4.tb.it, Chr5=chr5.tb.it, Chr6=chr6.tb.it)
tb.it$chr <- c(1:nrow(tb.it))
tbitm <- tb.it %>% gather(key, value, -chr)
colnames(tbitm) <- c("Individuals","Chromosome", "Proportions")
s4 <- ggplot(tbitm, aes(x=Individuals, y=Proportions, fill = Chromosome)) + geom_bar(stat="identity", position=position_dodge()) + scale_fill_manual(values=c("brown3", "magenta3", "cyan3", "gold3", "olivedrab3")) + theme_classic()
ggplot(tbitm, aes(x=Individuals, y=Proportions, fill = Chromosome)) + geom_bar(stat="identity", position=position_dodge()) + scale_fill_manual(values=c("brown3", "magenta3", "cyan3", "gold3", "olivedrab3")) + theme_classic()
ggsave("pe.gc.sfs.pdf",s1,height=8,width=15,units="cm",dpi=250)
ggsave("pe.it.sfs.pdf",s2,height=8,width=15,units="cm",dpi=250)
ggsave("tb.gc.sfs.pdf",s3,height=8,width=15,units="cm",dpi=250)
ggsave("tb.it.sfs.pdf",s4,height=8,width=15,units="cm",dpi=250)
quit()
